const ipcGeneral = {
	SET_WINDOW: 'SET_WINDOW',
	LOGIN_WINDOW: 'LOGIN_WINDOW',
	MIS_CLUB_PAGE_WINDOW: 'MIS_CLUB_PAGE_WINDOW',
	REQUEST_DIRECTORY_INFO: 'REQUEST_DIRECTORY_INFO'
};

const ipcMysql = {
	EXECUTE_SQL: 'EXECUTE_SQL',
	VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS',
	RETRIEVE_EVENTS_TODAY: 'RETRIEVE_EVENTS_TODAY',
	DELETE_EVENT: 'DELETE_EVENT',
	CREATE_EVENT: 'CREATE_EVENT',
	RETRIEVE_EVENT_BY_ID: 'RETRIEVE_EVENT_BY_ID',
	LOOKUP_NETID: 'LOOKUP_NETID',
	CHECK_IN_CREATE_MEMBER: 'CHECK_IN_CREATE_MEMBER',
	CHECK_IN_UPDATE_MEMBER: 'CHECK_IN_UPDATE_MEMBER',
	CREATE_MEMBER: 'CREATE_MEMBER',
	UPDATE_MEMBER: 'UPDATE_MEMBER',
	RETRIEVE_ATTENDANCE: 'RETRIEVE_ATTENDANCE',
	FIND_EVENTS: 'FIND_EVENTS'
};

// module.exports used because they are needed
// by main file 'electron.js' which
// is not bundled with webpack
module.exports = {
	ipcGeneral,
	ipcMysql
};
