const ipcGeneral = {
	SET_WINDOW: 'SET_WINDOW',
	LOGIN_WINDOW: 'LOGIN_WINDOW',
	MIS_CLUB_PAGE_WINDOW: 'MIS_CLUB_PAGE_WINDOW'
};

const ipcMysql = {
	RETRIEVE_SQL_DATA: 'RETRIEVE_SQL_DATA',
	RETRIEVE_EVENTS_TODAY: 'RETRIEVE_EVENTS_TODAY',
	DELETE_EVENT: 'DELETE_EVENT',
	ADD_EVENT: 'ADD_EVENT',
	RETRIEVE_EVENT_BY_ID: 'RETRIEVE_EVENT_BY_ID',
	VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS'
};

module.exports = {
	ipcGeneral,
	ipcMysql
};
